spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_it
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    correlation: [ "${ spring.application.name: },%X{ traceId:- },%X{ spanId:- }" ]
