spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoint:
    health:
      show:
        details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    correlation: [ "${ spring.application.name: },%X{ traceId:- },%X{ spanId:- }" ]

# Configuración CORS para desarrollo
app:
  cors:
    allowed-origins: 
      - http://localhost:3000    # React development
      - http://localhost:5173    # Vite development
      - http://localhost:4200    # Angular development
      - http://127.0.0.1:3000    # Localhost variants
      - http://127.0.0.1:5173
      - http://127.0.0.1:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600  # Cache preflight for 1 hour (development)
